sudo: required
dist: trusty

language: java
cache:
  directories:
  - $HOME/.gradle
jdk:
  - openjdk8
  - oraclejdk8

env: GRADLE_OPTS="-Xmx2500M"
before_install:
  # workaround to get "git describe" working
  - git fetch --unshallow --tags
  - git describe
  - ./gradlew setupCiWorkspace
#setupCIWorkspace is needed because of https://github.com/MinecraftForge/ForgeGradle/issues/410
# clean because of https://github.com/SpongePowered/MixinGradle/issues/4
script: ./gradlew clean build
deploy:
  - provider: script
    script: "./gradlew uploadArchives"
    skip_cleanup: true
    on:
      repo: OpenCubicChunks/CubicChunks
      all_branches: true

notifications:
  email: false
 
